server:
  session-timeout: 1800
  port: 8081
  servlet:
    context-path: /bootdo

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  cache:
    type: redis
    ehcache:
      config: classpath:config/ehcache.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain

mybatis-plus:
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true #驼峰下划线转换
      logic-delete-value: 0 #逻辑删除配置
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
